### ISSUE TITLE
Why compatible with .NET 2.0

### ISSUE THREAD

**Issue by suchja** [Tinkerforge/generators#42]
From what I see in source code it is important for Tinkerforge language binding in C# to be usable from .NET 2.0. Why is that?

Later versions of .NET provide many new feature (like TPL and async/await), which could improve (especially simplify) the language binding API. So it could be easier to use. At least to the extend I understand it.

As long as you could consider using a newer version of .NET I would be happy to provide some ideas / proposals how to improve the API.

Thanks for this awesome tools anyway.

**Comment by NobodysNightmare** [comment]
I think it is to reach a wide range of compatible software, since .NET 2.0 compatibility means a high degree of integratability.

Though I understand that this means not being able to use newer features.

I think if you wanted to refresh the bindings today, you would need to support both lines for a while, since there are a lot of tools using the old ones, too.

I am also not sure about Matematica and Co. IIRC the .NET bindings are used for some integrations with tools like matematica, not sure if they require .NET 2.0 or if they can handle 4.x, too...

**Comment by borg42** [comment]
As NobodysNightmare said, we need to be compatible with older versions of LabVIEW. We also want to be compatible to older linux distributions that may have a non-current mono version installed. The mono support for .NET 4.0 is relatively new. Similarly, there are probably some Windows Embedded device out there with old .NET versions that use Bricks and Bricklets etc.

Additionally, we don't do backwards-incompatible changes in the bindings. We did some incompatible changes when we completely changed the protocol. Maybe we will update the protocol again in the future.That would be a good time to do changes in the API. This is however something that will not happen earlier then in ~2 years. Until then we are working at full capacity with other already planned projects ;-).

I will close this issue for now.
