### ISSUE TITLE
(csharp) Socket disposed after consecutive timeouts

### ISSUE THREAD

**Issue by cristianbercu** [Tinkerforge/generators#52]
After several timeouts the wrapper disposes the socket and starts throwing ObjectDisposedException for Sockets.NetworkStream type. Shouldn't it kick in auto-reconnect if set and during this time shouldn't it set the IPConnection state to CONNECTION_STATE_DISCONNECTED or CONNECTION_STATE_PENDING instead?

Is this something that should have been done here?
https://github.com/Tinkerforge/generators/blob/master/csharp/IPConnection.cs#L2345

**Comment by photron** [comment]
The line of code you're referring to only applies in a UWP build of the Tinkerforge.dll, that is not shipped precompiled. Did you compile the Tinkerforge.dll yourself?

What timeout are you referring to? A timeout of the IPConnection.Connect() function or any other Brick/Bricklet setter/getter function?

**Comment by cristianbercu** [comment]
Ah, glad to hear that is not the actual c# Tinkerforge.dll, my bad for believeing otherwise. Is the code for the c# wrapper available anywhere publicly? 

On the other hand, I am trying to manage timeouts, in this case for a setter on a Bricklet. I am intentionally disconnecting the stack of bricks I have by removing the main connection cable so I produce timeouts. If I put back the connection cable and if the automatic reconnect is on shouldn't the IPConnection be re-established?

**Comment by photron** [comment]
Okay, lets first lock down what your actual setup is, I'm confused about it. At first, I thought you're running Windows 10 IoT Core on a Raspberry Pi and are programming an UWP app that runs along on the same Raspberry Pi, because you referred to a line of code that is relevant in that scenario only. The precompiled C# Tinkerforge.dll that is provided in the C# API bindings ZIP file does not handle that scenario. The precompiled C# Tinkerforge.dll covers the regular setup only. It has to be compiled from source with different compile time options for the Windows 10 IoT Core scenario.

The regular setup looks like this: You have a stack of Bricks and Bricklets that is connected to your regular PC using an USB cable. Your PC is running Brick Daemon to provide access to the USB connected Bricks and Bricklets using any of our API bindings, in your case the one for C#. If this is your setup then using the precompiled C# Tinkerforge.dll from the C# API bindings ZIP is the correct approach.

I think you're confusion two aspects of the API bindings. The IPConnection class manages a TCP/IP connection to Brick Daemon. The Connected and Disconnected callbacks of the IPConnection class only refer to the state of the TCP/IP connection to Brick Daemon. This has nothing to do with the USB connection of the stack. Disconnecting the stack from USB doesn't trigger an IPConnection Disconnected callback, instead it triggers an IPConnection Enumerate callback with enumerate type Disconnected for every disconnected Brick and Bricklet. Once you reconnect the stack to USB an IPConnection Enumerate callback with enumerate type Connected for every newly connected Brick and Bricklet is triggered. Have a look at the Enumerate example:

https://www.tinkerforge.com/en/doc/Software/IPConnection_CSharp.html#enumerate

The ObjectDisposedException shouldn't happen, regardless. Could you provide the source of your project, or a minimal example that produces the problem?

**Comment by cristianbercu** [comment]
Thanks for the detailed answer @photron and sorry for not being clear from the beginning. I am using the C# bindings and I thought the line of code I initially pointed out belongs to the TinkerForge.dll. You have made it clear that is not the case.

My setup is made of several bricks and bricklets to which I connect via ethernet cable over TCP/IP (or the tinkerforge protocol as my network sniffer names it) and I use the enumerate callback to check for connected components (to make sure everything is connected). I also authenticate the connection with a secret authentication token (if relevant).

I remove the ethernet cable to trigger timeouts on some setters and then I plug back the cable. The IPConnection should reconnect as I use SetAutoReconnect(true), right? At least this is my understanding of it.

Finally, no reconnection is established and after a few seconds I get a ObjectDisposedException.

**Comment by photron** [comment]
Well, a TCP/IP connection can only be closed actively by on of the two ends. Disconnecting the network cable doesn't constitute a disconnect on the TCP/IP level. That's the technical reason why you don't get a Disconnect callback for disconnecting the network cable. The TCP/IP connection is still fine and after reconnecting the network cable you can call setters again as normal.

I tried to reproduce the ObjectDisposedException, but it just works for me as expected and I don't get this error. Could you provide the source of your project, or a minimal example that produces the problem?

**Comment by cristianbercu** [comment]
Ah, that makes sense. The IPConnection is not aware of the physical state of the connection and it just tries to send packages to the already established connection. So I'll take a closer look at the connection on my end.
On the other hand, I will try to share here a code snippet that reproduces the error. Bear with me, and thanks in advance.
